### ISSUE TITLE
New Product Import Form - If we put in a MPN that is already used, with it recognize 

### ISSUE THREAD

**Issue by Mbanks89** [cbusillo/odoo_shiny#21]
This and not let us

**Comment by cbusillo** [comment]
Can you clarify what you are asking here?

It sounds like you want it to require MPN to be unique in the Product Import form only.  Meaning you can put in MPNs that exist in Odoo or Shopify, but not in the Product Import model.  That way they cannot duplicate an entry on the import screen, but you can create MPNs that already exist in Odoo.  Currently I believe you have duplicate MPN in Odoo.

**Comment by Mbanks89** [comment]
Will go into depth in person at the shop.  I believe this would only apply to new items.   

When we are going through all of this new inventory.

**Comment by cbusillo** [comment]
Done

**Comment by cbusillo** [comment]
![Screenshot 2023-07-06 at 2 10 42 AM](https://github.com/cbusillo/odoo_shiny/assets/1875516/5f9912c9-b9e4-48af-ba89-d9197699f4cc)
