### ISSUE TITLE
Multiple Bar Codes - Our Barcode MFN Barcode Etc

### ISSUE THREAD

**Issue by Mbanks89** [cbusillo/odoo_shiny#26]
Can there be a field where we can add a barcode?

**Comment by cbusillo** [comment]
Can you give me an example of what you would like to be a barcode?  If you are asking about scanning a MPN barcode, that should already work since we added MPN to the default search.  You can currently scan MPN, SKU, or BIN

**Comment by Mbanks89** [comment]
I know back in the day at the warehouse.   We would have our counterpoint barcode as the first one.  then if it had a Manufacturer barcode that would be second.  Maybe im not exactly understanding what a barcode is if im wording it wrong.

**Comment by cbusillo** [comment]
currently if you scan a barcode that has a mpn it will come up.  If you are saying the part might have another number, just show me what it looks like
