### ISSUE TITLE
MPN Search ebay / google

### ISSUE THREAD

**Issue by Mbanks89** [cbusillo/odoo_shiny#43]
Is it possible....  that when entering in new items into oDoo.  After you enter the MPN and click out of it, there could be a way where it opens a tab with google & ebay and puts that MPN in there and searches it?  I know this is odd and I dont know if this is even possible.  It would just save so much hassle of copying the MPN and then pasting it into google and ebay to search for pictures and prices.   It would kind of cut out the pre research portion of listing and you can do it while listing.   You may be able to implement it into your ebay stuff for rob.   Just a thought

 While im typing this I should probably just Ask chatGPT.   

ChatGPT says its possible.   This is by no means a must.  Just a cool feature that saves mouse clicks.   

![Screen Shot 2023-07-19 at 5 29 53 PM](https://github.com/cbusillo/odoo_shiny/assets/138520454/35a69f72-c0f7-48cd-aa8e-46dae416b7b7)

![Screen Shot 2023-07-19 at 5 29 57 PM](https://github.com/cbusillo/odoo_shiny/assets/138520454/cbd49b47-402f-4ff3-8419-af8de2483a69)

**Comment by cbusillo** [comment]
I added the feature as best I could.  It feels a little clunky to me.  Let me know if you have suggestions.  If its good enough, please close this issue.

**Comment by cbusillo** [comment]
Added open windows on field exit

**Comment by Mbanks89** [comment]
Going to play with it now

**Comment by Mbanks89** [comment]
I like this so far.    Im not sure if i'll like it while entering in new items one by one.   But i think this is something that will work but has room for improvements like everything.  Thank you for doing this
