### ISSUE TITLE
Auto Print Not working when creating new sku

### ISSUE THREAD

**Issue by Mbanks89** [cbusillo/odoo_shiny#45]
Auto-print is currently not working when creating a new SKU.   

Also, if it could print after you enter the quantity.  Then print that amount of labels.

With the manual print.  Is it possible to have an option where you can just print one label or quantity on hand?

**Comment by cbusillo** [comment]
Fixed.  it currently prints after entering in MPN and Quantity.  It prints the Bin label after Bin is entered.  It prints the quantity entered.  I can't think of a good way to print a different quantity than the quantity field.

**Comment by cbusillo** [comment]
Please close if this works.

**Comment by cbusillo** [comment]
Please reopen if not fixed.
