### ISSUE TITLE
Pictures Uploading in order

### ISSUE THREAD

**Issue by Mbanks89** [cbusillo/odoo_shiny#46]
Pictures are still not uploading in order.   The first set of skus imported were correct.  Then while working off of the same Odoo Import sheet, i did another set of 10 and so on.  The rest of the images were all out of order.  This may be something we need to work on together in person?

**Comment by cbusillo** [comment]
It's currently re importing all Shopify images so I can't do much for a while.  I added a way to sync Shopify image changes back to Odoo.  Now when you make changes to images or image order they will re download to Odoo.

**Comment by cbusillo** [comment]
Found it.  I forgot to order on index when saving into the Odoo products from products import.  I can't apply it till this sync finishes.
